name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v3
      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: |
          npm install
          pip install -r requirements.txt
      - name: Generate README file
        run: node index.js
      - name: Python
        run: python3 main.py
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}